### ISSUE TITLE
projectPublic member variable in Project isn't populated from "is_public" in JSON response 

### ISSUE THREAD

**Issue by ksperow** [taskadapter/redmine-java-api#245] opened 2016-04-12 16:31 UTC
As currently written the projectPublic member variable isn't being populated from the JSON response.

**Comment by alexeyOnGitHub** [comment] 2016-07-09 19:46
the corresponding Pull Request has been merged to the base version / master branch. the issue is resolved.

**Closed by alexeyOnGitHub** 2016-07-09 19:46 UTC
