### ISSUE TITLE
issue could not add watchers

### ISSUE THREAD

**Issue by rongbo** [taskadapter/redmine-java-api#317] opened 2019-03-18 07:56 UTC
Why was it that after I added watchers to issue, the actual issue was created successfully, but no watchers was found?In version 1.25

**Comment by javiertuya** [comment] 2019-04-08 20:53
Yo may try current version 3.1.2. There have been many improvements since 1.25, some of them related to watchers

**Comment by alexeyOnGitHub** [comment] 2020-01-01 02:11
closing this issue, there is no point in supporting version 1.25. feel free to reopen it and submit a PR with a fix if the issue is still reproducible with the current version

**Closed by alexeyOnGitHub** 2020-01-01 02:11 UTC
