### ISSUE TITLE
Parameter limit and offset are overwritten in Transport.getObjectsList()

### ISSUE THREAD

**Issue by a11n** [taskadapter/redmine-java-api#181] opened 2015-03-10 19:31 UTC
**Problem**
For `IssueManager.getIssues(Map<String, String> pParameters)` the documentation mentions:

```
@param pParameters the http parameters key/value pairs to append to the rest api request
```

When setting `offset` and `limit`like described in [official Redmine documentation](http://www.redmine.org/projects/redmine/wiki/Rest_Issues) these two parameters are ignored.

**Reason**
They are overwritten in Transport.getObjectsList() (line 413 and line 421)

**Suggestion**
A quick aid would be to mention this in the Javadoc of `getIssues()`. A more complex solution would be to ignore them if set in provided parameters. These would give redmine-java-api users more control, e.g. for implementing paging.

What do you think? Just tell me what you prefer, I could contribute an according pull request.

**Comment by alexeyOnGitHub** [comment] 2015-03-11 02:47
this is a duplicate of #114 
feel free to fix this

**Closed by alexeyOnGitHub** 2015-03-11 02:47 UTC
Labels: duplicate
