### ISSUE TITLE
Is it possible to put rest parameter in a container?

### ISSUE THREAD

**Issue by spellsleeper** [taskadapter/redmine-java-api#215] opened 2015-09-07 12:31 UTC
I've got one question, how is it possible to set more than one parameter with the same name?

A sample filter for issues:
<i>
final ConcurrentMap\<String, String\> parameters = new ConcurrentHashMap<>();
            parameters.put("f[]", "status_id");
            parameters.put("op[status_id]", "o");
            parameters.put("op[subject]", "~");
            parameters.put("set_filter", "1");
            issues = mainController.getIssueManager().getIssues(parameters);</i>

But when I'm filtering in redmine I've got params with the same name more than one time.
Redmine sample(firebug):
<i>
...
c[]	status
c[]	subject
c[]	assigned_to
c[]	due_date
f[]	status_id
f[]	assigned_to_id
...
</i>
Is it possible to put them in a container structure?

Why isn't it possible to put collections and other by JAXRS parseable types in a Map so that i can use a Map \<String,Object\>?

**Comment by spellsleeper** [comment] 2015-09-09 09:12
I've got a solution. It's a little bit dirty but it works and is faster than the standart way:

First I create an Transport in my Controller:
<i>
...
 private void createTransport(){
        transport=new Transport(new URIConfigurator(config.getRedmineUri(), 
                config.getRedmineApiAccessKey()),new DefaultHttpClient());
    }
...
</i>
Then I use  a Set with NameValuePairs to customize my Query and use the Transport object to get the results:
<i>
...
Set<NameValuePair> params =new HashSet<>();
        params.add(new BasicNameValuePair("f[]", "assigned_to_id"));
        params.add(new BasicNameValuePair("f[]", "status_id"));
        params.add(new BasicNameValuePair("op[status_id]", "o"));
        params.add(new BasicNameValuePair("op[subject]", "~"));
        params.add(new BasicNameValuePair("op[assigned_to_id]", "="));
        params.add(new BasicNameValuePair("v[assigned_to_id][]","me"));
        params.add(new BasicNameValuePair("set_filter", "1"));
        List<Issue> issues = null;
        try {
//            final MultiValueMap parameters = new MultiValueMap();
//            parameters.put("f[]", "assigned_to_id|status_id");
//            parameters.put("op[status_id]", "o");
//            parameters.put("op[subject]", "~");
//            parameters.put("op[assigned_to_id]", "=");
//            parameters.put("v[assigned_to_id][]","me");
//            parameters.put("set_filter", "1");
//            issues = mainController.getIssueManager().getIssues(parameters);
            issues=mainController.getTransport().getObjectsList(Issue.class, params);
        } catch (RedmineException ex) {
...
</i>

**Comment by alexeyOnGitHub** [comment] 2016-07-09 20:35
what is your use-case? what are you trying to do? what are those duplicated params you need to retrieve?

**Comment by tza** [comment] 2016-07-28 07:51
I think the use case is to query several fields which are exposed by the rest API via 
f[], op[subject], v[subject][] . With the current implementation and the HashMap, key f[] is overwritten. The rest API could handle several parameters of type f[] followed by additional information (op, v).

Issue #12 seems to address the same problem.

**Comment by alexeyOnGitHub** [comment] 2016-08-11 04:09
this looks like a duplicate of #12 indeed.

**Closed by alexeyOnGitHub** 2016-08-11 04:09 UTC
Labels: duplicate, question

**Comment by alexeyOnGitHub** [comment] 2016-08-11 05:21
I cannot find any documentation on the free-form search syntax in Redmine

**Comment by tza** [comment] 2016-08-11 05:41
On the [wiki](http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Listing-issues) I wasn't able to find this either. I guess the section "Optional filters" is not complete, since it ends with "..." 

I think I simple found the solution via the redmine ticket system itself: see [link](http://www.redmine.org/issues/8918).
It's possible to add custom filters with fields, operators and values. Shortcuts are f, op, and v.

**Comment by alexeyOnGitHub** [comment] 2016-08-11 15:38
thank you. I asked for docs on Redmine forum. let's see if someone can write up a simple wiki page on that. you are welcome to try the new API in this lib. see a sample test (failing) in issue #12

**Comment by tza** [comment] 2016-08-12 05:51
Thank you, I took a look and will write my feedback into ticket #12
