### ISSUE TITLE
uploadAttachment / downloadAttachmentToIssue doesn't works when file uploaded is big

### ISSUE THREAD

**Issue by Abbo44** [taskadapter/redmine-java-api#189] opened 2015-03-24 10:28 UTC
Hi, when i try to upload a png file, its ok, but when i try to upload a zip file or docx file i have this error: 
```
     org.json.JSONException: A JSONObject text must begin with '{' at character 1
com.taskadapter.redmineapi.RedmineFormatException: org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:567) ~[redmine-java-api-2.2.0.jar:?]
	at com.taskadapter.redmineapi.internal.Transport.upload(Transport.java:371) ~[redmine-java-api-2.2.0.jar:?]
	at com.taskadapter.redmineapi.AttachmentManager.uploadAttachment(AttachmentManager.java:136) ~[redmine-java-api-2.2.0.jar:?]
	at com.taskadapter.redmineapi.AttachmentManager.uploadAttachment(AttachmentManager.java:80) ~[redmine-java-api-2.2.0.jar:?]
```

I tried to use this code, and the function downloadAttachmentToIssue but both doens't work for docx and zip files.

    attachment = mgr.getAttachmentManager().uploadAttachment(fileJeuxDonnees.getName(), "application/zip", IOUtils.toByteArray(bytesFile));

with 
    File fileJeuxDonnees = new File(confFicheFile);
    bytesFile = new FileInputStream(fileJeuxDonnees);

**Comment by alexeyOnGitHub** [comment] 2015-03-25 00:25
Do you have a fix for this issue by any chance?

**Comment by Abbo44** [comment] 2015-03-25 07:47
No , i did lot of test but no one worked. But i test only on a png file, a docx file & a zip file.

**Comment by Abbo44** [comment] 2015-03-27 16:13
Have u some news ? I need to upload Zip & docx file for my work, and some guys are blocked cuz of this ^^

**Comment by Abbo44** [comment] 2015-03-27 16:58
Have u try to use a  `JSONArray`

**Comment by alexeyOnGitHub** [comment] 2015-03-28 03:08
I don't see anyone willing to work on attachments code soon. is it possible for you to investigate this and provide a fix?

**Comment by Abbo44** [comment] 2015-03-30 08:22
Yes i checkout the project i will try to find a solution.

**Comment by Abbo44** [comment] 2015-03-31 14:15
I tried extension jar too and doesn't work. Jpeg works.
I think its an invalid JSON request. 
But i don't find solutions yet..
Still working but if u can help me it will be great ! ;)

**Comment by Abbo44** [comment] 2015-04-13 10:07
On the function upload(InputStream content), i have this on the result parameter : 
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Bad Gateway</title>
</head><body>
<h1>Bad Gateway</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at redmine-ext.euriware.fr Port 443</address>
</body></html>

**Comment by Abbo44** [comment] 2015-04-14 08:15
After some research, the extension file isn't the problem.
The file's length is the real cause of the problem.
Someone had the same issue than me  : http://www.redmine.org/issues/17888

I'm on it.

**Comment by alexeyOnGitHub** [comment] 2015-10-16 06:21
I suppose this is a duplicate of issue #78 .

**Closed by alexeyOnGitHub** 2015-10-16 06:21 UTC
Labels: duplicate
