### ISSUE TITLE
Ability to assign issues to groups

### ISSUE THREAD

**Issue by akurutin** [taskadapter/redmine-java-api#256] opened 2016-07-19 10:06 UTC
http://www.redmine.org/issues/2964 was added in  redmine version 1.3, but taskadapter 2.6.0 cant assignee group to new Issue.

**Comment by alexeyOnGitHub** [comment] 2016-07-19 23:22
duplicate of #213   . already implemented in "master" branch. not released to Maven Central until some other things are finalized (e.g. updating fields which would be a breaking API change and thus releasing this as a part of 3.0.0 would make sense).
we can release 3.0.0.alpha or something but we would need to release the final 3.0.0  version with the breaking API changes anyway, so..

**Closed by alexeyOnGitHub** 2016-07-19 23:22 UTC
Labels: duplicate
