### ISSUE TITLE
Add deleting attachments 

### ISSUE THREAD

**Issue by Abbo44** [taskadapter/redmine-java-api#198] opened 2015-05-20 14:07 UTC
REST Api upgraded one year ago for add deleting attachments enhancment.
Can you add this functionality to redmine java api please ?

http://www.redmine.org/issues/14828

Thank you.

**Comment by Abbo44** [comment] 2015-05-21 12:44
https://github.com/taskadapter/redmine-java-api/issues/106

**Comment by alexeyOnGitHub** [comment] 2015-07-07 07:50
this is a duplicate of #106 
also, the patch you mentioned was never merged into the main Redmine codebase (as of today anyway). so it is not available in Redmine's REST API.

**Closed by alexeyOnGitHub** 2015-07-07 07:50 UTC
Labels: enhancement

**Comment by alexeyOnGitHub** [comment] 2016-07-10 18:29
I see the Redmine patch was merged 3 months ago. now we can add support to the Java library
