### ISSUE TITLE
SSL SNI extension support

### ISSUE THREAD

**Issue by brunojcm** [taskadapter/redmine-java-api#221] opened 2015-10-14 17:52 UTC
httpclient before 4.3.2 doesn't support SNI, as the following link says:
https://issues.apache.org/jira/browse/HTTPCLIENT-1119

It can generate some exceptions like:

```
Exception in thread "main" com.taskadapter.redmineapi.RedmineTransportException: Cannot fetch data from https://company.plan.io/users.json : javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:57)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineAuthenticator.sendRequest(RedmineAuthenticator.java:52)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.BasicSimplifier.sendRequest(BasicSimplifier.java:24)
	at com.taskadapter.redmineapi.internal.Transport.send(Transport.java:572)
	at com.taskadapter.redmineapi.internal.Transport.getObjectsListNoPaging(Transport.java:447)
	at com.taskadapter.redmineapi.internal.Transport.getObjectsList(Transport.java:416)
	at com.taskadapter.redmineapi.internal.Transport.getObjectsList(Transport.java:393)
	at com.taskadapter.redmineapi.UserManager.getUsers(UserManager.java:81)
	at br.com.company.redmineReport.Report2.main(Report2.java:28)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:641)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:45)
	... 10 more
```

Any problems in upgrading to 4.3.2+?

**Comment by alexeyOnGitHub** [comment] 2015-10-15 04:54
I got non-deterministic behavior with HttpClient 4.5.1. see https://github.com/taskadapter/redmine-java-api/issues/212   you are welcome to debug and fix this.

**Comment by alexeyOnGitHub** [comment] 2015-10-15 04:54
duplicate of #212

**Closed by alexeyOnGitHub** 2015-10-15 04:54 UTC
Labels: duplicate

**Comment by alexeyOnGitHub** [comment] 2015-10-18 18:42
the new HttpClient version dependency is merged into "master". see Issue #212
