### ISSUE TITLE
downloadAttachmentContent works only with UserAuth and no with ApiKeyAuth

### ISSUE THREAD

**Issue by Abbo44** [taskadapter/redmine-java-api#197] opened 2015-05-18 15:16 UTC
Hello,

When we use the function 

``` 
Issue previousIssue = mgr.getIssueManager().getIssueById(Integer.parseInt(id), Include.attachments);
for (Attachment attachment : attachments) {
Attachment finalAttachment = downloadAttachmentContent(attachment);
}
```
It doesn't works because we need an authentification with login and Password in the java File :
RedmineAuthenticator.java

**Comment by Abbo44** [comment] 2015-05-20 14:16
Linked to https://github.com/taskadapter/redmine-java-api/issues/121

**Comment by alexeyOnGitHub** [comment] 2015-10-16 06:18
I assume this is a duplicate of issue #121

**Closed by alexeyOnGitHub** 2015-10-16 06:18 UTC
Labels: duplicate
