### ISSUE TITLE
Error Create Issue

### ISSUE THREAD

**Issue by adrianobr** [taskadapter/redmine-java-api#234] opened 2015-12-30 19:04 UTC
Version Redmine 3.2
Version API JAVA Maven 2.6.0

Example Redmine API Java for Create an issue
Issue issue = IssueFactory.createWithSubject("test123");
Version ver = VersionFactory.create(512);
issue.setTargetVersion(ver);
IssueCategory cat = IssueCategoryFactory.create(673);
issue.setCategory(cat);
ProjectManager projectManager = manager.getProjectManager();
Project projectByKey = projectManager.getProjectByKey("testid");
issue.setProject(projectByKey);
manager.getIssueManager().createIssue(issue);

Exception in thread "main" com.taskadapter.redmineapi.RedmineFormatException: org.json.JSONException: JSONObject["issue"] not found.
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:590)
	at com.taskadapter.redmineapi.internal.Transport.addObject(Transport.java:229)
	at com.taskadapter.redmineapi.IssueManager.createIssue(IssueManager.java:173)
	at br.com.sysmo.principal.Principal.criandoCategorias(Principal.java:76)
	at br.com.sysmo.principal.Principal.main(Principal.java:36)
Caused by: org.json.JSONException: JSONObject["issue"] not found.
	at org.json.JSONObject.get(JSONObject.java:498)
	at org.json.JSONObject.getJSONObject(JSONObject.java:592)
	at com.taskadapter.redmineapi.internal.json.JsonInput.getObjectNotNull(JsonInput.java:344)
	at com.taskadapter.redmineapi.internal.RedmineJSONParser.getResponseSingleObject(RedmineJSONParser.java:706)
	at com.taskadapter.redmineapi.internal.Transport.parseResponse(Transport.java:588)

**Comment by alexeyOnGitHub** [comment] 2016-01-04 03:43
does it work on older versions of Redmine for you? maybe Redmine devs broke backward compatibility again.

**Comment by adrianobr** [comment] 2016-01-04 15:30
I did not get to test!
any plans to run for the latest versions?

**Comment by alexeyOnGitHub** [comment] 2016-07-09 20:15
all tests currently pass on Redmine 3.2.3. can you reproduce this issue with the latest code in "master" branch?

**Comment by adrianobr** [comment] 2016-07-09 20:19
hello, I use maven
https://mvnrepository.com/artifact/com.taskadapter/redmine-java-api/2.6.0

It is expected to update the package maven?

**Comment by alexeyOnGitHub** [comment] 2016-07-09 20:32
the latest code is not available in maven central. there were multiple commits in "master" since version 2.6.0 that is in Maven Central.

**Comment by alexeyOnGitHub** [comment] 2016-08-09 02:47
this has been open for 8+ months with no recent information. closing it.

**Closed by alexeyOnGitHub** 2016-08-09 02:47 UTC
